version: "3"
x-env_vars: &rust_env_vars
  environment:
    RUST_LOG: ${RUST_LOG}
    RUST_BACKTRACE: ${RUST_BACKTRACE}
services:
  frontend:
    build: ./frontend
    <<: *rust_env_vars
    tty: true
    container_name: tg_frontend
  backend:
    build: ./backend
    <<: *rust_env_vars
    environment:
      BACKEND_HOST: ${BACKEND_HOST:-"0.0.0.0:8081"}
      DATABASE_URL: postgres://${POSTGRES_USER?}:${POSTGRES_PASSWORD?}@database/${POSTGRES_DB?}
    depends_on:
      - database
    tty: true
    container_name: tg_backend
  database:
    image: "postgres:13.3"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?}
      POSTGRES_DB: ${POSTGRES_DB?}
    container_name: tg_database
