version: "3"
services:
  frontend:
    volumes:
      - fecargo:/usr/local/cargo
    environment:
      WASM_PROFILE: release
  backend:
    ports:
      - "8081:8081"
    volumes:
      - becargo:/usr/local/cargo
  database:
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  fecargo:
  becargo:
  db:
