version: "3"
services:
  frontend:
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app
      - fecargo:/usr/local/cargo
  backend:
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/usr/src/app
      - becargo:/usr/local/cargo
  database:
    environment:
      POSTGRES_USER: tguser
      POSTGRES_PASSWORD: tgpassword
      POSTGRES_DB: tgdb
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  fecargo:
  becargo:
  db:
