version: "3"
services:
  database:
    image: "postgres"
    environment:
      POSTGRES_USER: tguser
      POSTGRES_PASSWORD: tgpassword
      POSTGRES_DB: tgdb
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: tg_database
volumes:
  db:
