version: "3"
services:
  frontend:
    volumes:
      - fecargo:/usr/local/cargo
    environment:
      WASM_PROFILE: release
  backend:
    volumes:
      - becargo:/usr/local/cargo
  database:
    environment:
      POSTGRES_USER: ${POSTGRES_USER?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?}
      POSTGRES_DB: ${POSTGRES_DB?}
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  fecargo:
  becargo:
  db:
