[package]
name = "backend"
version = "0.1.0"
authors = ["Julius Lungys <32368314+voidpumpkin@users.noreply.github.com>"]
edition = "2018"

[package.metadata.commands]
dev = "cargo watch -x run"

[dependencies]
actix-web = "3.3.2"
